// svelte-openlayers/src/lib/OlVectorLayer.svelte
<script lang="ts">

  import {getContext, onMount, onDestroy} from 'svelte';
  import {Map } from 'ol';
  import VectorLayer from 'ol/layer/Vector';
  import VectorSource from 'ol/source/Vector';
  import {key} from './ol-common.ts'
  import type {StyleLike} from "ol/style/Style";
  import Feature from "ol/Feature";

  export let style : StyleLike;
  export let features: Array<Feature> = [];

	const { getMap } = getContext(key);
	const map:Map = getMap();

  const vectorLayer = new VectorLayer({
    source: new VectorSource({ features }),
    style,
  });

  onMount(() => {
    map.addLayer(vectorLayer);
  });
  onDestroy(() => {
    map.removeLayer(vectorLayer);
  });

  let prevFeatures = [];
  $: {
    console.log(features.length, prevFeatures.length)
    prevFeatures = features;
    const source : VectorSource = vectorLayer.getSource();
    source.clear();
    source.addFeatures(features);
  }
</script>

<div></div>

<style>
</style>

// vue3-map-chart-timeline/src/components/ol-vector-layer.vue
<script setup>
//import {createEmpty, extend} from 'ol/extent';
import VectorLayer from 'ol/layer/Vector';
import VectorSource from 'ol/source/Vector';
import { makeAllExtent } from '../ol-utils';

import { ref, watch, onMounted, onUnmounted, provide, inject } from 'vue'

const props = defineProps({
  style: Function | Object,
  features: Array, 
})

const map = inject('map')

const vectorLayer = new VectorLayer({
  source: new VectorSource({
    features: props.features,
  }),
  style: props.style,
});

watch(
  ()=> props.style, 
  (style, old)=>{
    vectorLayer.setStyle(style)
  }
)
watch(
  ()=> props.features, 
  (features, oldValues)=>{
    vectorLayer.getSource().clear()
    vectorLayer.getSource().addFeatures(features)
    //map.getView().fit( makeAllExtent(features))
  }
)

onMounted(() => {
  map.addLayer(vectorLayer)
})
onUnmounted(()=>{
  map.removeLayer(vectorLayer)
})
provide('vectorLayer', vectorLayer)

</script>

<template>
  <div></div>
</template>

<style scoped>
.mapContainer {
  width: 100%;
  height: 100%;
}
</style>
