// vue3-map-chart-timeline/src/components/ol-map.vue
<script setup>
import {Map, View} from 'ol';
import TileLayer from 'ol/layer/Tile';
//import VectorLayer from 'ol/layer/Vector';
//import VectorSource from 'ol/source/Vector';

import {DAUM_ROAD_MAP} from '../ol-daum.js'
 
import { ref, watch, onMounted, onUnmounted, provide } from 'vue'

function level2zoom(level){
  return 14-level + 3
}
const props = defineProps({
  center: Array, 
  level: Number,
})

const mapRef = ref(null)

let map = new Map({
  layers: [
    new TileLayer({
      className: 'baseMap',
      source: DAUM_ROAD_MAP,
    }),
  ],
  view: new View({
    center: props.center,
    zoom: level2zoom(props.level)
  }),
});

watch(
  ()=> props.center, 
  (oldValue, newVaule)=>{
    map.getView().setCenter(newVaule)
  }
)
watch(
  ()=> props.level, 
  (oldValue, newVaule)=>{
    map.getView().setZoom(level2zoom(newVaule))
  }
)

onMounted(() => {
  map.setTarget(mapRef.value)
})
onUnmounted(()=>{
  map.setTarget(null)
  map = null;
})
provide('map', map)

</script>

<template>
  <div ref="mapRef" class="mapContainer">
    <slot></slot>
  </div>
</template>

<style scoped>
.mapContainer {
  width: 100%;
  height: 100%;
}
</style>

// svelte-openlayers/src/lib/OlMap.svelte
<script lang="ts">
  import 'ol/ol.css';

  import {setContext, onMount} from 'svelte';
  import {Map, View} from 'ol';
  import TileLayer from 'ol/layer/Tile';
  import {key} from './ol-common.ts'

  import {DAUM_ROAD_MAP} from '../ol-daum.js'

  export let center: [number, number];
  export let level: number;

  function level2zoom(level){
    return 14-level + 3
  }

  let container;
  let map: Map;

  onMount(()=>{
    map = new Map({
      target: container,
      layers: [
        new TileLayer({
          source: DAUM_ROAD_MAP,
        }),
      ],
      view: new View({
        center: center,
        zoom: level2zoom(level)
      }),
    });
  });

  setContext(key, {
    getMap : ()=> map
  })

</script>

<div bind:this={container} style="width: 100%; height: 100%">
  {#if map}
    <slot/>
  {/if}
</div>

<style>
</style>
